#!/usr/bin/env python
"""make_kaggle_kernel.py — generate the v2 Kaggle kernel that trains the REAL Laya RLCD
loop on 2×T4 (replacing the T5 seq2seq kernel — see KAGGLE_RUN_REVIEW_20260923.md).

Embeds mcp_finetune/train.py verbatim into a single-cell kernel script so the kernel
never drifts from the local trainer: regenerate this file after every train.py change.

Output: kaggle/kernel_v2/laya_rlcd_v2.py (+ kernel-metadata.json if missing)

Tulpa push steps:
  cd kaggle/kernel_v2
  # keep v1's dataset attachment (combined-all.jsonl): copy "dataset_sources" from the
  # v1 kernel metadata (kaggle kernels metadata qalarc/laya-combined-fine-tune)
  kaggle kernels push
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "kaggle" / "kernel_v2"

PRELUDE = """\
# Laya RLCD fine-tune (typed decisions) — NOT seq2seq.
# GENERATED by scripts/make_kaggle_kernel.py from mcp_finetune/train.py — do not hand-edit.
# Trains convaiinnovations/laya with the GRPO-style proper-scoring-rule loop,
# per-bucket temperature calibration, and the hard gate (agreement>=0.85, ECE<=0.10).
# Output: /kaggle/working/ckpt (laya.load() format + eval.json gate table).

import base64, glob, sys

candidates = glob.glob("/kaggle/input/**/combined-all.jsonl", recursive=True)
assert candidates, "combined-all.jsonl not found in /kaggle/input"
DATA = candidates[0]

print("installing laya…", flush=True)
import subprocess
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "laya==0.3.5"], check=True)

TRAIN_SOURCE = base64.b64decode("__B64__").decode()
compile(TRAIN_SOURCE, "train_embedded.py", "exec")  # sanity before running

train_globals = {"__name__": "__train__", "__file__": "/kaggle/working/train_embedded.py"}
exec(TRAIN_SOURCE, train_globals)

sys.argv = [
    "train.py",
    "--dataset", DATA,
    "--epochs", "3",
    "--micro-batch", "16",
    "--grad-accum", "2",
    "--device", "cuda",
    "--out", "/kaggle/working/ckpt",
]
try:
    train_globals["main"]()
except SystemExit as e:  # train.py exits non-zero on gate FAIL — keep the kernel "done"
    print(f"train.py exited with {e.code} (gate FAIL = exit 1; checkpoint + eval.json still saved)", flush=True)

print("=== GATE TABLE (eval.json) ===", flush=True)
print(open("/kaggle/working/ckpt/eval.json").read(), flush=True)
print("checkpoint at /kaggle/working/ckpt — download and finetune_register ONLY on gate PASS", flush=True)

# ---- publish the run output to the Qalarc HF org (PRIVATE) ------------------------
# Owner-approved wiring (2026-09-23): kernel → Qalarc/laya-combined-all, private.
# Needs the HF_TOKEN Kaggle Secret attached (Add-ons → Secrets) — skips gracefully
# if absent. eval.json rides along so gate PASS/FAIL is auditable on the hub.
# Registration into serve.py stays a LOCAL step (finetune_register), never automatic.
try:
    from kaggle_secrets import UserSecretsClient
    import json as _json
    _hf_token = UserSecretsClient().get_secret("HF_TOKEN")
    from huggingface_hub import HfApi
    _api = HfApi(token=_hf_token)
    _repo = "Qalarc/laya-combined-all"
    _api.create_repo(_repo, private=True, exist_ok=True)
    _gate = "?"
    try:
        _gate = _json.load(open("/kaggle/working/ckpt/eval.json")).get("gate", "?")
    except Exception:
        pass
    _api.upload_folder(
        repo_id=_repo, repo_type="model",
        folder_path="/kaggle/working/ckpt",
        commit_message=f"kaggle 2xT4 run {time.strftime('%Y%m%d-%H%M')} gate={_gate}",
    )
    print(f"uploaded checkpoint (gate={_gate}) -> https://huggingface.co/{_repo} (private)", flush=True)
except Exception as _e:
    print(f"HF upload skipped: {_e}", flush=True)
    print("(attach the HF_TOKEN Kaggle Secret to auto-publish: Add-ons → Secrets → attach)", flush=True)
"""


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    train_src = (ROOT / "mcp_finetune" / "train.py").read_text()
    assert "proper_reward" in train_src, "train.py does not look like the RLCD version"
    import base64 as _b64

    kernel = PRELUDE.replace("__B64__", _b64.b64encode(train_src.encode()).decode())
    (OUT / "laya_rlcd_v2.py").write_text(kernel)
    meta_path = OUT / "kernel-metadata.json"
    if not meta_path.is_file():
        meta_path.write_text(
            json.dumps(
                {
                    "id": "qalarc/laya-rlcd-v2",
                    "title": "laya-rlcd-v2",
                    "code_file": "laya_rlcd_v2.py",
                    "language": "python",
                    "kernel_type": "script",
                    "is_private": "true",
                    "enable_gpu": "true",
                    "enable_internet": "true",
                    # combined-all dataset attachment (same as v1) — DO NOT push without it
                    "dataset_sources": ["qalarc/qalarc-laya-combined-decisions"],
                    "competition_sources": [],
                    "kernel_sources": [],
                },
                indent=2,
            )
            + "\n"
        )
    # sanity: the generated kernel must be valid python
    compile(kernel, "laya_rlcd_v2.py", "exec")
    print(
        f"wrote {OUT / 'laya_rlcd_v2.py'} ({len(kernel):,} chars) + metadata — compiles OK"
    )


if __name__ == "__main__":
    main()
